export default {
    main: {
        appVer: '1.0',
        // sigMethod: 'SHA256withRSA',
        sigMethod: {
            level1: 'HMACSHA256',
            level2: 'SHA256withRSA'
        },
        callerZone: ['WWW', 'Internet Zone', 'Intranet Zone', 'SGNet'],
        providerGateway: ['External Gateway', 'Internal Gateway'],
        authLevels: [0, 1, 2],
        defaultGateway: "apex_example_gateway",
        defaultUri: "/apex/example/path",
        defaultAuthPrefix: "Apex",
        notificationShowTime : 5000,
        domain: process.env.NODE_ENV === "production" ? ".api.gov.sg" : ".api.dev",
        errorMsgs :{
            noSelectedGateway: "Gateway must be specified",
            noAuthPrefix: "Auth prefix must be specified",
            noAppId : "Application Id must be specified",
            noAppSecret: "Application Secret must be specified",
            timestampInvalid : "Timestamp must be specified if not autogenerated",
            nonceInvalid : "Nonce must be specified if not autogenerated",
            noPemProvided: "Please load or enter a valid PEM formatted private key",
            pemSecretInvalid : "Please verify that both pem string and secret are correct",
            httpReqError: "Error encountered while making the request. Please refer to the readme for possible causes."
        }
    },
    sign: {
        beginPrivateRSA: "-----BEGIN RSA PRIVATE KEY-----",
        endPrivRSA: "-----END RSA PRIVATE KEY-----",
        beginCert: "-----BEGIN CERTIFICATE-----",
        endCert: "-----END CERTIFICATE-----"
    },
    test: {
        levels: [0, 1, 2]
    }
}
